gfraser4_College_Strike/Controllers/AssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gfraser4_College_Strike.Data;
using gfraser4_College_Strike.Models;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.AspNetCore.Authorization;
//Graeme Fraser
//Project Part 5
namespace gfraser4_College_Strike.Controllers
{
    [Authorize]
    public class AssignmentsController : Controller
    {
        private readonly CollegeStrikeContext _context;

        public AssignmentsController(CollegeStrikeContext context)
        {
            _context = context;
        }

        // GET: Assignments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Assignments.ToListAsync());
        }

        // GET: Assignments/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var assignment = await _context.Assignments
            //    .FirstOrDefaultAsync(m => m.ID == id);

            var assignments = _context.Assignments
                .Include(m => m.Members)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (assignments == null)
            {
                return NotFound();
            }

            return View(await assignments);
        }

        // GET: Assignments/Create
        [Authorize(Roles = "Steward,Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Assignments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Steward,Admin")]
        public async Task<IActionResult> Create([Bind("ID,AssignmentName")] Assignment assignment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(assignment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(assignment);
        }

        // GET: Assignments/Edit/5
        [Authorize(Roles = "Steward,Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments.FindAsync(id);
            if (assignment == null)
            {
                return NotFound();
            }
            return View(assignment);
        }

        // POST: Assignments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Steward,Admin")]
        public async Task<IActionResult> Edit(int id, Byte[] RowVersion)
        {

            //Go get the Doctor to update
            var assignmentToUpdate = await _context.Assignments.SingleOrDefaultAsync(p => p.ID == id);
            //Check that you got it or exit with a not found error
            if (assignmentToUpdate == null)
            {
                return NotFound();
            }

            //Try updating it with the values posted
            if (await TryUpdateModelAsync<Assignment>(assignmentToUpdate, "",
                a => a.AssignmentName))
            {
                try
                {
                    _context.Entry(assignmentToUpdate).Property("RowVersion").OriginalValue = RowVersion;
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
                }

                catch (DbUpdateConcurrencyException ex)
                {
                    var exceptionEntry = ex.Entries.Single();
                    var clientValues = (Assignment)exceptionEntry.Entity;
                    var databaseEntry = exceptionEntry.GetDatabaseValues();
                    if (databaseEntry == null)
                    {
                        ModelState.AddModelError("",
                            "Unable to save changes. The Patient was deleted by another user.");
                    }
                    else
                    {
                        var databaseValues = (Assignment)databaseEntry.ToObject();
                        if (databaseValues.AssignmentName != clientValues.AssignmentName)
                            ModelState.AddModelError("AssignmentName", "Current value: "
                                + databaseValues.AssignmentName);
                        ModelState.AddModelError(string.Empty, "The record you attempted to edit "
                                + "was modified by another user after you received your values. The "
                                + "edit operation was canceled and the current values in the database "
                                + "have been displayed. If you still want to save your version of this record, click "
                                + "the Save button again. Otherwise click the 'Back to List' hyperlink.");
                        assignmentToUpdate.RowVersion = (byte[])databaseValues.RowVersion;
                        ModelState.Remove("RowVersion");
                    }
                }
                catch (DbUpdateException dex)
                {
                    if (dex.InnerException.Message.Contains("IX_Assignments_AssignmentName"))
                    {
                        ModelState.AddModelError("AssignmentName", "Unable to save changes. Remember, you cannot have Assignment names.");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                    }
                }

            }
            //Validaiton Error so give the user another chance.
            return View(assignmentToUpdate);
        }

        // GET: Assignments/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assignment = await _context.Assignments
                .FirstOrDefaultAsync(m => m.ID == id);
            if (assignment == null)
            {
                return NotFound();
            }

            return View(assignment);
        }

        // POST: Assignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var assignment = await _context.Assignments.FindAsync(id);
            _context.Assignments.Remove(assignment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AssignmentExists(int id)
        {
            return _context.Assignments.Any(e => e.ID == id);
        }
    }
}

gfraser4_College_Strike/Controllers/ShiftsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gfraser4_College_Strike.Data;
using gfraser4_College_Strike.Models;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.AspNetCore.Authorization;
//Graeme Fraser
//Project Part 5
namespace gfraser4_College_Strike.Controllers
{
    [Authorize(Roles = "Steward,Admin")]
    public class ShiftsController : Controller
    {
        private readonly CollegeStrikeContext _context;

        public ShiftsController(CollegeStrikeContext context)
        {
            _context = context;
        }

        // GET: Shifts
        public async Task<IActionResult> Index()
        {
            ViewData["MemberID"] = new SelectList(_context.Members
                .OrderBy(c => c.FullName), "ID", "FullName");
            PopulateDropDownLists();
            ViewData["Filtering"] = "";

            ViewData["AssignmentID"] = new SelectList(_context.Assignments
                .OrderBy(c => c.AssignmentName), "ID", "AssignmentName");
            PopulateDropDownLists();
            ViewData["Filtering"] = "";

            var collegeStrikeContext = _context.Shifts.Include(s => s.Assignment).Include(s => s.Member);
            return View(await collegeStrikeContext.ToListAsync());
        }

        // GET: Shifts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shift = await _context.Shifts
                .Include(s => s.Assignment)
                .Include(s => s.Member)
                .FirstOrDefaultAsync(m => m.AssignmentID == id);
            if (shift == null)
            {
                return NotFound();
            }

            return View(shift);
        }

        // GET: Shifts/Create
        public IActionResult Create()
        {
            var shift = new Shift();
            PopulateDropDownLists();
            return View();
        }

        // POST: Shifts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ShiftDate,AssignmentID,MemberID")] Shift shift)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shift);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            PopulateDropDownLists(shift);
            return View(shift);
        }

        // GET: Shifts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shift = await _context.Shifts.FindAsync(id);
            if (shift == null)
            {
                return NotFound();
            }
            PopulateDropDownLists(shift);
            return View(shift);
        }

        // POST: Shifts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Byte[] RowVersion)
        {
            //Go get the patient to update
            var shiftToUpdate = await _context.Shifts.SingleOrDefaultAsync(p => p.ID == id);
            //Check that you got it or exit with a not found error
            if (shiftToUpdate == null)
            {
                return NotFound();
            }

            //Try updating it with the values posted
            if (await TryUpdateModelAsync<Shift>(shiftToUpdate, "",
                s => s.ShiftDate, s => s.MemberID, s => s.AssignmentID))
            {
                try
                {
                    _context.Entry(shiftToUpdate).Property("RowVersion").OriginalValue = RowVersion;
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    var exceptionEntry = ex.Entries.Single();
                    var clientValues = (Shift)exceptionEntry.Entity;
                    var databaseEntry = exceptionEntry.GetDatabaseValues();
                    if (databaseEntry == null)
                    {
                        ModelState.AddModelError("",
                            "Unable to save changes. The Patient was deleted by another user.");
                    }
                    else
                    {
                        var databaseValues = (Shift)databaseEntry.ToObject();
                        if (databaseValues.ShiftDate != clientValues.ShiftDate)
                            ModelState.AddModelError("ShiftDate", "Current value: "
                                + databaseValues.ShiftDate);
                        if (databaseValues.AssignmentID != clientValues.AssignmentID)
                        {
                            Assignment databaseAssignment = await _context.Assignments.SingleOrDefaultAsync(i => i.ID == databaseValues.AssignmentID);
                            ModelState.AddModelError("AssignmentID", $"Current value: {databaseAssignment?.AssignmentName}");
                        }
                        if (databaseValues.MemberID != clientValues.MemberID)
                        {
                            Member databaseMember = await _context.Members.SingleOrDefaultAsync(i => i.ID == databaseValues.MemberID);
                            ModelState.AddModelError("MemberID", $"Current value: {databaseMember?.FullName}");
                        }
                        ModelState.AddModelError(string.Empty, "The record you attempted to edit "
                                + "was modified by another user after you received your values. The "
                                + "edit operation was canceled and the current values in the database "
                                + "have been displayed. If you still want to save your version of this record, click "
                                + "the Save button again. Otherwise click the 'Back to List' hyperlink.");
                        shiftToUpdate.RowVersion = (byte[])databaseValues.RowVersion;
                        ModelState.Remove("RowVersion");
                    }
                }
                catch (DbUpdateException dex)
                {
                    if (dex.InnerException.Message.Contains("IX_Shift_ShiftDate_MemberID"))
                    {
                        ModelState.AddModelError("ShiftDate", "Unable to save changes. Remember, you cannot a duplicate member on the same date.");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                    }
                }
            }
            //Validaiton Error so give the user another chance.
            PopulateDropDownLists(shiftToUpdate);
            return View(shiftToUpdate);
        }

        // GET: Shifts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shift = await _context.Shifts
                .Include(s => s.Assignment)
                .Include(s => s.Member)
                .FirstOrDefaultAsync(m => m.AssignmentID == id);
            if (shift == null)
            {
                return NotFound();
            }

            return View(shift);
        }

        // POST: Shifts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shift = await _context.Shifts.FindAsync(id);
            _context.Shifts.Remove(shift);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private void PopulateDropDownLists(Shift shift = null)
        {
            var aQuery = from a in _context.Assignments
                         orderby a.AssignmentName
                         select a;
            var mQuery = from m in _context.Members
                         orderby m.FullName
                         select m;
            ViewData["AssignmentID"] = new SelectList(aQuery, "ID", "AssignmentName", shift?.AssignmentID);
            ViewData["MemberID"] = new SelectList(mQuery, "ID", "FullName", shift?.MemberID);
        }

        private bool ShiftExists(int id)
        {
            return _context.Shifts.Any(e => e.AssignmentID == id);
        }
    }
}

gfraser4_College_Strike/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - gfraser4_College_Strike</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">gfraser4_College_Strike</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Assignments" asp-action="Index">Assignments</a></li>
                        <li><a asp-area="" asp-controller="Members" asp-action="Index">Members</a></li>
                    }
                    @if (User.IsInRole("Steward") || User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Shifts" asp-action="Index">Shifts</a></li>
                    }

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - gfraser4_College_Strike</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

gfraser4_College_Strike/Views/Shared/_PagingNavBar.cshtml
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled='disabled'" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled='disabled'" : "";
}
<nav aria-label="..." class="nav navbar-fixed-bottom">
    <ul class="pager">
        <li>
            <button type="submit" name="page" value="1" @prevDisabled class="btn btn-default">
                <span aria-hidden="true">&lArr;</span>&nbsp;First
            </button>
        </li>
        <li>
            <button type="submit" name="page" @prevDisabled value="@(Model.PageIndex - 1)" class="btn btn-default">
                <span aria-hidden="true">&larr;</span>&nbsp;Previous
            </button>
        </li>
        <li class="badge"><span class="text-primary">Page @Model.PageIndex of @Model.TotalPages</span></li>
        <li>
            <button type="submit" name="page" @nextDisabled value="@(Model.PageIndex + 1)" class="btn btn-default">
                Next&nbsp;<span aria-hidden="true">&rarr;</span>
            </button>
        </li>
        <li>
            <button type="submit" name="page" @nextDisabled value="@(Model.TotalPages)" class="btn btn-default">
                Last&nbsp;<span aria-hidden="true">&rArr;</span>
            </button>
        </li>
    </ul>
</nav>